/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace BetOnChain {
  export type AchievementRequirementStruct = {
    beginnerNumberOfBets: PromiseOrValue<BigNumberish>;
    warriorNumberOfBets: PromiseOrValue<BigNumberish>;
    expertNumberOfBets: PromiseOrValue<BigNumberish>;
  };

  export type AchievementRequirementStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    beginnerNumberOfBets: BigNumber;
    warriorNumberOfBets: BigNumber;
    expertNumberOfBets: BigNumber;
  };

  export type AchievementURIStruct = {
    beginner: PromiseOrValue<string>;
    warrior: PromiseOrValue<string>;
    expert: PromiseOrValue<string>;
  };

  export type AchievementURIStructOutput = [string, string, string] & {
    beginner: string;
    warrior: string;
    expert: string;
  };
}

export interface BetOnChainInterface extends utils.Interface {
  functions: {
    "addressToBetToPlayer(address,uint256)": FunctionFragment;
    "bet(uint256,uint256,uint256)": FunctionFragment;
    "bets(uint256)": FunctionFragment;
    "bocNFT()": FunctionFragment;
    "bocToken()": FunctionFragment;
    "closeBet(uint256)": FunctionFragment;
    "createBet(uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
    "getAchievementRequirement()": FunctionFragment;
    "getAchievementURI()": FunctionFragment;
    "getBetPositionURI()": FunctionFragment;
    "mintAchievementNft(uint256)": FunctionFragment;
    "numberOfBets(address)": FunctionFragment;
    "openBet(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "playerBets(uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setAchievementRequirement(uint256,uint256,uint256)": FunctionFragment;
    "setAchievementURI(string,string,string)": FunctionFragment;
    "setBetPositionURI(string)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "withdrawPrize(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addressToBetToPlayer"
      | "bet"
      | "bets"
      | "bocNFT"
      | "bocToken"
      | "closeBet"
      | "createBet"
      | "getAchievementRequirement"
      | "getAchievementURI"
      | "getBetPositionURI"
      | "mintAchievementNft"
      | "numberOfBets"
      | "openBet"
      | "owner"
      | "playerBets"
      | "renounceOwnership"
      | "setAchievementRequirement"
      | "setAchievementURI"
      | "setBetPositionURI"
      | "transferOwnership"
      | "withdrawPrize"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addressToBetToPlayer",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "bet",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "bets",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "bocNFT", values?: undefined): string;
  encodeFunctionData(functionFragment: "bocToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "closeBet",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "createBet",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAchievementRequirement",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAchievementURI",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBetPositionURI",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintAchievementNft",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "numberOfBets",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "openBet",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "playerBets",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAchievementRequirement",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setAchievementURI",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setBetPositionURI",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPrize",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "addressToBetToPlayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bocNFT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bocToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "closeBet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAchievementRequirement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAchievementURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBetPositionURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintAchievementNft",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numberOfBets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "openBet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "playerBets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAchievementRequirement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAchievementURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBetPositionURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPrize",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface BetOnChain extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BetOnChainInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addressToBetToPlayer(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber] & {
        player: string;
        betAmount: BigNumber;
        betFor: BigNumber;
        nftId: BigNumber;
      }
    >;

    bet(
      betAmount: PromiseOrValue<BigNumberish>,
      betFor: PromiseOrValue<BigNumberish>,
      betId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    bets(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, boolean, BigNumber] & {
        betFor1: BigNumber;
        betFor2: BigNumber;
        oddsfor1: BigNumber;
        oddsfor2: BigNumber;
        betsOpen: boolean;
        totalBetAmount: BigNumber;
      }
    >;

    bocNFT(overrides?: CallOverrides): Promise<[string]>;

    bocToken(overrides?: CallOverrides): Promise<[string]>;

    closeBet(
      betId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createBet(
      betId: PromiseOrValue<BigNumberish>,
      betFor1: PromiseOrValue<BigNumberish>,
      betFor2: PromiseOrValue<BigNumberish>,
      oddsfor1: PromiseOrValue<BigNumberish>,
      oddsfor2: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getAchievementRequirement(
      overrides?: CallOverrides
    ): Promise<[BetOnChain.AchievementRequirementStructOutput]>;

    getAchievementURI(
      overrides?: CallOverrides
    ): Promise<[BetOnChain.AchievementURIStructOutput]>;

    getBetPositionURI(overrides?: CallOverrides): Promise<[string]>;

    mintAchievementNft(
      achievementLevelToMint: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    numberOfBets(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    openBet(
      betId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    playerBets(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber] & {
        player: string;
        betAmount: BigNumber;
        betFor: BigNumber;
        nftId: BigNumber;
      }
    >;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setAchievementRequirement(
      beginnerNumberOfBets: PromiseOrValue<BigNumberish>,
      warriorNumberOfBets: PromiseOrValue<BigNumberish>,
      expertNumberOfBets: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setAchievementURI(
      beginnerURI: PromiseOrValue<string>,
      warriorURI: PromiseOrValue<string>,
      expertURI: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setBetPositionURI(
      _betPositionURI: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawPrize(
      betId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  addressToBetToPlayer(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, BigNumber] & {
      player: string;
      betAmount: BigNumber;
      betFor: BigNumber;
      nftId: BigNumber;
    }
  >;

  bet(
    betAmount: PromiseOrValue<BigNumberish>,
    betFor: PromiseOrValue<BigNumberish>,
    betId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  bets(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, boolean, BigNumber] & {
      betFor1: BigNumber;
      betFor2: BigNumber;
      oddsfor1: BigNumber;
      oddsfor2: BigNumber;
      betsOpen: boolean;
      totalBetAmount: BigNumber;
    }
  >;

  bocNFT(overrides?: CallOverrides): Promise<string>;

  bocToken(overrides?: CallOverrides): Promise<string>;

  closeBet(
    betId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createBet(
    betId: PromiseOrValue<BigNumberish>,
    betFor1: PromiseOrValue<BigNumberish>,
    betFor2: PromiseOrValue<BigNumberish>,
    oddsfor1: PromiseOrValue<BigNumberish>,
    oddsfor2: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getAchievementRequirement(
    overrides?: CallOverrides
  ): Promise<BetOnChain.AchievementRequirementStructOutput>;

  getAchievementURI(
    overrides?: CallOverrides
  ): Promise<BetOnChain.AchievementURIStructOutput>;

  getBetPositionURI(overrides?: CallOverrides): Promise<string>;

  mintAchievementNft(
    achievementLevelToMint: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  numberOfBets(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  openBet(
    betId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  playerBets(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, BigNumber] & {
      player: string;
      betAmount: BigNumber;
      betFor: BigNumber;
      nftId: BigNumber;
    }
  >;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setAchievementRequirement(
    beginnerNumberOfBets: PromiseOrValue<BigNumberish>,
    warriorNumberOfBets: PromiseOrValue<BigNumberish>,
    expertNumberOfBets: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setAchievementURI(
    beginnerURI: PromiseOrValue<string>,
    warriorURI: PromiseOrValue<string>,
    expertURI: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setBetPositionURI(
    _betPositionURI: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawPrize(
    betId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addressToBetToPlayer(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber] & {
        player: string;
        betAmount: BigNumber;
        betFor: BigNumber;
        nftId: BigNumber;
      }
    >;

    bet(
      betAmount: PromiseOrValue<BigNumberish>,
      betFor: PromiseOrValue<BigNumberish>,
      betId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    bets(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, boolean, BigNumber] & {
        betFor1: BigNumber;
        betFor2: BigNumber;
        oddsfor1: BigNumber;
        oddsfor2: BigNumber;
        betsOpen: boolean;
        totalBetAmount: BigNumber;
      }
    >;

    bocNFT(overrides?: CallOverrides): Promise<string>;

    bocToken(overrides?: CallOverrides): Promise<string>;

    closeBet(
      betId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    createBet(
      betId: PromiseOrValue<BigNumberish>,
      betFor1: PromiseOrValue<BigNumberish>,
      betFor2: PromiseOrValue<BigNumberish>,
      oddsfor1: PromiseOrValue<BigNumberish>,
      oddsfor2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getAchievementRequirement(
      overrides?: CallOverrides
    ): Promise<BetOnChain.AchievementRequirementStructOutput>;

    getAchievementURI(
      overrides?: CallOverrides
    ): Promise<BetOnChain.AchievementURIStructOutput>;

    getBetPositionURI(overrides?: CallOverrides): Promise<string>;

    mintAchievementNft(
      achievementLevelToMint: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    numberOfBets(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    openBet(
      betId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    playerBets(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber] & {
        player: string;
        betAmount: BigNumber;
        betFor: BigNumber;
        nftId: BigNumber;
      }
    >;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setAchievementRequirement(
      beginnerNumberOfBets: PromiseOrValue<BigNumberish>,
      warriorNumberOfBets: PromiseOrValue<BigNumberish>,
      expertNumberOfBets: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setAchievementURI(
      beginnerURI: PromiseOrValue<string>,
      warriorURI: PromiseOrValue<string>,
      expertURI: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setBetPositionURI(
      _betPositionURI: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawPrize(
      betId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    addressToBetToPlayer(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bet(
      betAmount: PromiseOrValue<BigNumberish>,
      betFor: PromiseOrValue<BigNumberish>,
      betId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    bets(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bocNFT(overrides?: CallOverrides): Promise<BigNumber>;

    bocToken(overrides?: CallOverrides): Promise<BigNumber>;

    closeBet(
      betId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createBet(
      betId: PromiseOrValue<BigNumberish>,
      betFor1: PromiseOrValue<BigNumberish>,
      betFor2: PromiseOrValue<BigNumberish>,
      oddsfor1: PromiseOrValue<BigNumberish>,
      oddsfor2: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getAchievementRequirement(overrides?: CallOverrides): Promise<BigNumber>;

    getAchievementURI(overrides?: CallOverrides): Promise<BigNumber>;

    getBetPositionURI(overrides?: CallOverrides): Promise<BigNumber>;

    mintAchievementNft(
      achievementLevelToMint: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    numberOfBets(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    openBet(
      betId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    playerBets(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setAchievementRequirement(
      beginnerNumberOfBets: PromiseOrValue<BigNumberish>,
      warriorNumberOfBets: PromiseOrValue<BigNumberish>,
      expertNumberOfBets: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setAchievementURI(
      beginnerURI: PromiseOrValue<string>,
      warriorURI: PromiseOrValue<string>,
      expertURI: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setBetPositionURI(
      _betPositionURI: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawPrize(
      betId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addressToBetToPlayer(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bet(
      betAmount: PromiseOrValue<BigNumberish>,
      betFor: PromiseOrValue<BigNumberish>,
      betId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    bets(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bocNFT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bocToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    closeBet(
      betId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createBet(
      betId: PromiseOrValue<BigNumberish>,
      betFor1: PromiseOrValue<BigNumberish>,
      betFor2: PromiseOrValue<BigNumberish>,
      oddsfor1: PromiseOrValue<BigNumberish>,
      oddsfor2: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getAchievementRequirement(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAchievementURI(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getBetPositionURI(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mintAchievementNft(
      achievementLevelToMint: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    numberOfBets(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    openBet(
      betId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    playerBets(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setAchievementRequirement(
      beginnerNumberOfBets: PromiseOrValue<BigNumberish>,
      warriorNumberOfBets: PromiseOrValue<BigNumberish>,
      expertNumberOfBets: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setAchievementURI(
      beginnerURI: PromiseOrValue<string>,
      warriorURI: PromiseOrValue<string>,
      expertURI: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setBetPositionURI(
      _betPositionURI: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawPrize(
      betId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
