/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BetOnChain } from "./BetOnChain";
export type { BocNFT } from "./BocNFT";
export type { BocToken } from "./BocToken";
export type { ExchangeToken } from "./ExchangeToken";
