/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BetOnChain__factory } from "./BetOnChain__factory";
export { BocNFT__factory } from "./BocNFT__factory";
export { BocToken__factory } from "./BocToken__factory";
export { ExchangeToken__factory } from "./ExchangeToken__factory";
